import { Router } from 'express';
import menuRoutes from './menu';
import moduleRoutes from './module';
import imeiRoutes from './imei';
import dataRoutes from './data';
import timeOfActivitieRoutes from './activities_duration/activities_duration';
import trameRoutes from './trame';
import vidangeRoutes from './vidange';
import regionRoutes from './region';
import userRoutes from './users';
import authRoutes from './auth';
import roleRoutes from './role';
const router = Router();
//router.use('/menu', menuRoutes);
router.use('/modules',moduleRoutes);
router.use('/trames',trameRoutes);
router.use('/vidanges',vidangeRoutes);
router.use('/imei',imeiRoutes);
router.use('/data',dataRoutes);
router.use('/timeOfActivities',timeOfActivitieRoutes);
router.use('/regions',regionRoutes);
router.use('/users',userRoutes);
router.use('/auth',authRoutes);
router.use('/roles',roleRoutes);
export default router;
